# Generated by Django 4.0.4 on 2022-05-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='numero')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('fechaDeEntrada', models.CharField(max_length=50, verbose_name='fecha_de_entrada')),
                ('estado', models.CharField(max_length=50, verbose_name='estado')),
                ('cuenta', models.CharField(max_length=30, verbose_name='cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=30, verbose_name='cuenta')),
                ('sector', models.CharField(max_length=30, verbose_name='sector')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('dni', models.IntegerField(verbose_name='dni')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('sectorCoordinador', models.CharField(max_length=30, verbose_name='sector_coordinador')),
            ],
        ),
    ]
